spring:
  application:
    name: MealDB

  cache:
    type: redis   # Enable Redis caching

  data:
    redis:
      host: localhost   # Redis server host
      port: 6379        # Default Redis port
      timeout: 60000    # Connection timeout in ms

server:
  port: 8081   

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
